apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}: {{- .Values.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "216m"
        ports:
        - containerPort: 8080
          name: backend-port
      imagePullSecrets: 
      - name: backend-docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 8080
    targetPort: backend-port
    nodePort: {{ .Values.service.nodePort }}