apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    {{- include "gulfcam-frontend-chart.labels" . }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls: 
  - hosts:
    {{- range .Values.ingress.hosts }}
      - {{ .name }}
    {{- end }}
{{- end }}
    secretName: front-end-secret
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .name}}
    http:
        paths:
        - pathType: {{.pathType }}
          path: {{ .path | quote }}
          backend:
            service:
              name: {{ .backendService }}
              port: 
                number: {{ .port }}
{{- end -}}