apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: front-deny-ingress
spec:
  podSelector: 
    matchLabels:
      app: front-end-deployment
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: 
        matchLabels:
          app: back-end-deployment