apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gulfcam-frontend-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: front-end-deployment
  template:
    metadata:
      labels:
        app: front-end-deployment
    spec:
      containers:
      - name: front-end-deployment
        image: {{ .Values.image.repository }}: {{- .Values.image.tag }}
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name : front-end-port
      imagePullSecrets: 
      {{ with .Values.imagePullSecrets }}
      {{- toYaml . }}
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: NodePort
  selector:
    app: front-end-deployment
  ports:
  - port: 8080
    targetPort: front-end-port
    nodePort: {{ .Values.nodePort }}
